"""add document model

Revision ID: 2256f2469750
Revises: 5d13bad4fa8d
Create Date: 2026-06-16 19:21:50.340756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2256f2469750'
down_revision = '5d13bad4fa8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicule', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('kilometrage',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('marque',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('transmission',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('places',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicule', schema=None) as batch_op:
        batch_op.alter_column('places',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('transmission',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('marque',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('kilometrage',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(),
               nullable=True)

    op.drop_table('document')
    # ### end Alembic commands ###
