"""add vehicule table

Revision ID: 5d13bad4fa8d
Revises: fca2975ad393
Create Date: 2026-06-09 10:43:48.219855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d13bad4fa8d'
down_revision = "fca2975ad393"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('kilometrage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('marque', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('transmission', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('places', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('vehicule_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicule', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('vehicule_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('places')
        batch_op.drop_column('transmission')
        batch_op.drop_column('marque')
        batch_op.drop_column('kilometrage')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
