"""revenu_mensuel nullable

Revision ID: 79203316cdf8
Revises: 2256f2469750
Create Date: 2026-06-22 11:42:44.750955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79203316cdf8'
down_revision = '2256f2469750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dossier', schema=None) as batch_op:
        batch_op.alter_column('revenu_mensuel',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dossier', schema=None) as batch_op:
        batch_op.alter_column('revenu_mensuel',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
