"""add dossier table

Revision ID: fca2975ad393
Revises: 
Create Date: 2026-06-08 22:26:54.445170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca2975ad393'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicule_id', sa.Integer(), nullable=False),
    sa.Column('type_financement', sa.String(), nullable=False),
    sa.Column('revenu_mensuel', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicule_id'], ['vehicule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dossier')
    # ### end Alembic commands ###
